### ISSUE TITLE
Quartical attempts to write products even when the outputs are empty

### ISSUE THREAD

**Issue by sjperkins** [ratt-ru/QuartiCal#195]
**Describe the bug**

While testing Quartical on a read-only S3 dataset, with outputs configured as follows:

```yaml
output:
  directory: outputs.qc
  overwrite: true
  products:
  columns:
  flags: false
  apply_p_jones_inv: false
  subtract_directions:
  net_gain: false
```

Quartical still tries to write something to the input location resulting in the following stack trace

<details> <summary>Access Denied exception  </summary>

```python
2022-09-12 07:16:08 | ERROR | goquartical:<module> | An error has been caught in function '<module>', process 'MainProcess' (5324), thread 'MainThread' (140105246732736):
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/dist-packages/s3fs/core.py", line 110, in _error_wrapper
    return await func(*args, **kwargs)
                 │     │       └ {'Bucket': 'ratt-public-data', 'Key': 'ESO137/ms1_primary_subset.zarr/MAIN/MAIN_0/.zattrs', 'Body': b'{\n    "DATA_DESC_ID": ...
                 │     └ ()
                 └ <bound method ClientCreator._create_api_method.<locals>._api_call of <aiobotocore.client.S3 object at 0x7f6c647cbc10>>
  File "/usr/local/lib/python3.10/dist-packages/aiobotocore/client.py", line 358, in _make_api_call
    raise error_class(parsed_response, operation_name)
          │           │                └ 'PutObject'
          │           └ {'Error': {'Code': 'AccessDenied', 'Message': 'Access Denied'}, 'ResponseMetadata': {'RequestId': 'PC0VEJJGAG28GFE5', 'HostId...
          └ <class 'botocore.exceptions.ClientError'>

botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

> File "/usr/local/bin/goquartical", line 8, in <module>
    sys.exit(execute())
    │   │    └ <function execute at 0x7f6c66298c10>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/lib/python3.10/dist-packages/quartical/executor.py", line 33, in execute
    _execute(stack)
    │        └ <contextlib.ExitStack object at 0x7f6ccb32fc10>
    └ <function _execute at 0x7f6c66298ca0>
  File "/usr/local/lib/python3.10/dist-packages/quartical/executor.py", line 143, in _execute
    ms_writes = write_xds_list(data_xds_list,
                │              └ [<xarray.Dataset>
                │                Dimensions:              (row: 98332, chan: 500, dir: 1, corr: 4, uvw: 3,
                │                                          ant: 61...
                └ <function write_xds_list at 0x7f6c67911120>
  File "/usr/local/lib/python3.10/dist-packages/quartical/data_handling/ms_handler.py", line 279, in write_xds_list
    write_xds_list = xds_to_storage_table(
                     └ <function xds_to_storage_table at 0x7f6c6dec6560>
  File "/usr/local/lib/python3.10/dist-packages/daskms/dask_ms.py", line 374, in xds_to_storage_table
    return xds_to_zarr(xds, store, **kwargs)
           │           │    │        └ {'columns': (), 'rechunk': True}
           │           │    └ DaskMSStore(s3://ratt-public-data/ESO137/ms1_primary_subset.zarr)
           │           └ [<xarray.Dataset>
           │             Dimensions:              (row: 98332, chan: 500, dir: 1, corr: 4, uvw: 3,
           │                                       ant: 61...
           └ <function xds_to_zarr at 0x7f6c66fd2c20>
  File "/usr/local/lib/python3.10/dist-packages/daskms/experimental/zarr/__init__.py", line 294, in xds_to_zarr
    ds, group = prepare_zarr_group(di, ds, store, rechunk=rechunk)
    │           │                  │   │   │              └ True
    │           │                  │   │   └ DaskMSStore(s3://ratt-public-data/ESO137/ms1_primary_subset.zarr)
    │           │                  │   └ <xarray.Dataset>
    │           │                  │     Dimensions:  ()
    │           │                  │     Data variables:
    │           │                  │         *empty*
    │           │                  │     Attributes:
    │           │                  │         DATA_DESC_ID:                 0
    │           │                  │         FIELD_ID:   ...
    │           │                  └ 0
    │           └ <function prepare_zarr_group at 0x7f6c66fd28c0>
    └ <xarray.Dataset>
      Dimensions:  ()
      Data variables:
          *empty*
      Attributes:
          DATA_DESC_ID:                 0
          FIELD_ID:   ...
  File "/usr/local/lib/python3.10/dist-packages/daskms/experimental/zarr/__init__.py", line 112, in prepare_zarr_group
    dataset, ds_group = maybe_rechunk(dataset, ds_group, rechunk=rechunk)
    │                   │             │        │                 └ True
    │                   │             │        └ <zarr.hierarchy.Group '/MAIN/MAIN_0'>
    │                   │             └ <xarray.Dataset>
    │                   │               Dimensions:  ()
    │                   │               Data variables:
    │                   │                   *empty*
    │                   │               Attributes:
    │                   │                   DATA_DESC_ID:                 0
    │                   │                   FIELD_ID:   ...
    │                   └ <function maybe_rechunk at 0x7f6c66fd29e0>
    └ <xarray.Dataset>
      Dimensions:  ()
      Data variables:
          *empty*
      Attributes:
          DATA_DESC_ID:                 0
          FIELD_ID:   ...
  File "/usr/local/lib/python3.10/dist-packages/daskms/experimental/zarr/__init__.py", line 173, in maybe_rechunk
    group.attrs.update({
    │     └ <property object at 0x7f6c6de70590>
    └ <zarr.hierarchy.Group '/MAIN/MAIN_0'>
  File "/usr/local/lib/python3.10/dist-packages/zarr/attrs.py", line 157, in update
    self._write_op(self._update_nosync, *args, **kwargs)
    │    │         │    │                │       └ {}
    │    │         │    │                └ ({'__daskms_zarr_attr__': {'chunks': {}}},)
    │    │         │    └ <function Attributes._update_nosync at 0x7f6c6e27a0e0>
    │    │         └ <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>
    │    └ <function Attributes._write_op at 0x7f6c6e279c60>
    └ <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>
  File "/usr/local/lib/python3.10/dist-packages/zarr/attrs.py", line 83, in _write_op
    return f(*args, **kwargs)
           │  │       └ {}
           │  └ ({'__daskms_zarr_attr__': {'chunks': {}}},)
           └ <bound method Attributes._update_nosync of <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>>
  File "/usr/local/lib/python3.10/dist-packages/zarr/attrs.py", line 171, in _update_nosync
    self._put_nosync(d)
    │    │           └ {'DATA_DESC_ID': 0, 'FIELD_ID': 0, 'SCAN_NUMBER': 1, '__daskms_partition_schema__': [['FIELD_ID', 'int32'], ['DATA_DESC_ID', ...
    │    └ <function Attributes._put_nosync at 0x7f6c6e279fc0>
    └ <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>
  File "/usr/local/lib/python3.10/dist-packages/zarr/attrs.py", line 132, in _put_nosync
    self.store[self.key] = json_dumps(d)
    │    │     │    │      │          └ {'DATA_DESC_ID': 0, 'FIELD_ID': 0, 'SCAN_NUMBER': 1, '__daskms_partition_schema__': [['FIELD_ID', 'int32'], ['DATA_DESC_ID', ...
    │    │     │    │      └ <function json_dumps at 0x7f6c6e261990>
    │    │     │    └ 'MAIN/MAIN_0/.zattrs'
    │    │     └ <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>
    │    └ <KVStore: 
    │      <fsspec.mapping.FSMap object at 0x7f6c5cb1efb0>
    │       at 0x7f6c5ff451b0>
    └ <zarr.attrs.Attributes object at 0x7f6c5cc1bc10>
  File "/usr/local/lib/python3.10/dist-packages/zarr/storage.py", line 720, in __setitem__
    self._mutable_mapping[key] = value
    │    │                │      └ b'{\n    "DATA_DESC_ID": 0,\n    "FIELD_ID": 0,\n    "SCAN_NUMBER": 1,\n    "__daskms_partition_schema__": [\n        [\n    ...
    │    │                └ 'MAIN/MAIN_0/.zattrs'
    │    └ <fsspec.mapping.FSMap object at 0x7f6c5cb1efb0>
    └ <KVStore: 
      <fsspec.mapping.FSMap object at 0x7f6c5cb1efb0>
       at 0x7f6c5ff451b0>
  File "/usr/local/lib/python3.10/dist-packages/fsspec/mapping.py", line 156, in __setitem__
    self.fs.pipe_file(key, maybe_convert(value))
    │    │  │         │    │             └ b'{\n    "DATA_DESC_ID": 0,\n    "FIELD_ID": 0,\n    "SCAN_NUMBER": 1,\n    "__daskms_partition_schema__": [\n        [\n    ...
    │    │  │         │    └ <function maybe_convert at 0x7f6cc9d72200>
    │    │  │         └ 'ratt-public-data/ESO137/ms1_primary_subset.zarr/MAIN/MAIN_0/.zattrs'
    │    │  └ <function S3FileSystem._pipe_file at 0x7f6c6478f5b0>
    │    └ <s3fs.core.S3FileSystem object at 0x7f6c6632a3b0>
    └ <fsspec.mapping.FSMap object at 0x7f6c5cb1efb0>
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           │    │    │     │      │       └ {}
           │    │    │     │      └ ('ratt-public-data/ESO137/ms1_primary_subset.zarr/MAIN/MAIN_0/.zattrs', b'{\n    "DATA_DESC_ID": 0,\n    "FIELD_ID": 0,\n    ...
           │    │    │     └ <bound method S3FileSystem._pipe_file of <s3fs.core.S3FileSystem object at 0x7f6c6632a3b0>>
           │    │    └ <property object at 0x7f6c662f0540>
           │    └ <s3fs.core.S3FileSystem object at 0x7f6c6632a3b0>
           └ <function sync at 0x7f6c6629b520>
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
          └ PermissionError('Access Denied')
  File "/usr/local/lib/python3.10/dist-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
    │                 └ <coroutine object S3FileSystem._pipe_file at 0x7f6c5c738ba0>
    └ [PermissionError('Access Denied')]
  File "/usr/local/lib/python3.10/dist-packages/s3fs/core.py", line 962, in _pipe_file
    return await self._call_s3(
                 │    └ <function S3FileSystem._call_s3 at 0x7f6c6477ff40>
                 └ <s3fs.core.S3FileSystem object at 0x7f6c6632a3b0>
  File "/usr/local/lib/python3.10/dist-packages/s3fs/core.py", line 332, in _call_s3
    return await _error_wrapper(
                 └ <function _error_wrapper at 0x7f6c6477fac0>
  File "/usr/local/lib/python3.10/dist-packages/s3fs/core.py", line 137, in _error_wrapper
    raise err
          └ PermissionError('Access Denied')

PermissionError: Access Denied
```

See log in attached zip

</details>

**Data description (if applicable)**

``s3://ratt-public-data/ESO137/ms1_primary_subset.zarr/``

**To Reproduce**

``goquartical user_config.yaml``

See user_config.yaml in attached zip

**Expected behavior**

Quartical runs on a read-only datasource

**Screenshots**

**Version**

See freeze.txt in attached zip

[info.zip](https://github.com/ratt-ru/QuartiCal/files/9545769/info.zip)

**Comment by JSKenyon** [comment]
Thanks for the report. I believe that this is likely due to the fact that the write code is called even when there are no columns to be written. Should be a simple fix.

**Comment by JSKenyon** [comment]
#196 Should fix this, if you would like to review. Just escapes the write if no columns are going to be written.

**Comment by sjperkins** [comment]
@landmanbester do you think pfb-clean might have similar concerns?

**Comment by landmanbester** [comment]
I doubt it. Writes only get added to the graph if there is something to write
