### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/QuartiCal#249]
Currently the dependency resolver takes ages to resolve dependencies (see below part of the output (Python 3.8, latest available setuptools wheel and pip). This is for the release version quartical==0.1.10 

This can be fixed by appropriate version pinning as I've done for DDFacet and KillMS (and I think is the preferred solution to ensure stability in the installs).

```
...
Collecting distributed (from quartical)
  Downloading distributed-1.14.3-py2.py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.4/235.4 kB 96.8 MB/s eta 0:00:00
  Downloading distributed-1.14.1-py2.py3-none-any.whl (228 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.1/228.1 kB 93.2 MB/s eta 0:00:00
  Downloading distributed-1.14.0-py2.py3-none-any.whl (227 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.9/227.9 kB 83.0 MB/s eta 0:00:00
  Downloading distributed-1.13.3-py2.py3-none-any.whl (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.0/214.0 kB 108.3 MB/s eta 0:00:00
  Downloading distributed-1.13.2-py2.py3-none-any.whl (208 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.4/208.4 kB 91.8 MB/s eta 0:00:00
  Downloading distributed-1.13.1-py2.py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.7/207.7 kB 92.8 MB/s eta 0:00:00
  Downloading distributed-1.13.0-py2.py3-none-any.whl (207 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.7/207.7 kB 87.3 MB/s eta 0:00:00
  Downloading distributed-1.12.2-py2.py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.1/203.1 kB 82.2 MB/s eta 0:00:00
  Downloading distributed-1.12.1-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.5/199.5 kB 108.3 MB/s eta 0:00:00
Collecting boto3 (from distributed->quartical)
  Downloading boto3-1.26.125-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 80.9 MB/s eta 0:00:00
Collecting distributed (from quartical)
  Downloading distributed-1.12.0-py2.py3-none-any.whl (185 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 185.4/185.4 kB 93.7 MB/s eta 0:00:00
  Downloading distributed-1.11.3-py2.py3-none-any.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.4/179.4 kB 104.9 MB/s eta 0:00:00
  Downloading distributed-1.11.2-py2.py3-none-any.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.6/174.6 kB 96.2 MB/s eta 0:00:00
  Downloading distributed-1.11.1-py2.py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.3/163.3 kB 83.1 MB/s eta 0:00:00
  Downloading distributed-1.11.0-py2.py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.8/109.8 kB 76.3 MB/s eta 0:00:00
  Downloading distributed-1.10.2-py2.py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.6/106.6 kB 68.0 MB/s eta 0:00:00
  Downloading distributed-1.10.1-py2.py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 74.4 MB/s eta 0:00:00
  Downloading distributed-1.10.0-py2.py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.0/106.0 kB 72.2 MB/s eta 0:00:00
  Downloading distributed-1.9.5-py2.py3-none-any.whl (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.1/125.1 kB 80.5 MB/s eta 0:00:00
  Downloading distributed-1.9.4-py2.py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.0/124.0 kB 83.6 MB/s eta 0:00:00
  Downloading distributed-1.9.3-py2.py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.3/126.3 kB 85.0 MB/s eta 0:00:00
  Downloading distributed-1.9.2-py2.py3-none-any.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.4/121.4 kB 74.4 MB/s eta 0:00:00
  Downloading distributed-1.9.1-py2.py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.3/92.3 kB 68.0 MB/s eta 0:00:00
  Downloading distributed-1.9.0-py2.py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 kB 57.7 MB/s eta 0:00:00
  Downloading distributed-1.8.1.tar.gz (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 80.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.8.0.tar.gz (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.0/109.0 kB 62.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.7.4.tar.gz (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.8/98.8 kB 61.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.7.3.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 54.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.7.2.tar.gz (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB 56.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.7.1-py2.py3-none-any.whl (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 43.2 MB/s eta 0:00:00
  Downloading distributed-1.7.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.3/60.3 kB 46.3 MB/s eta 0:00:00
  Downloading distributed-1.6.1.tar.gz (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.7/80.7 kB 63.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting paramiko (from distributed->quartical)
  Downloading paramiko-3.1.0-py3-none-any.whl (211 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.2/211.2 kB 75.2 MB/s eta 0:00:00
Collecting distributed (from quartical)
  Downloading distributed-1.6.0.tar.gz (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 59.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.5.0.tar.gz (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.4/63.4 kB 43.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.4.0.tar.gz (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 41.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.3.3.tar.gz (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 36.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dill (from distributed->quartical)
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 79.2 MB/s eta 0:00:00
Collecting distributed (from quartical)
  Downloading distributed-1.3.2.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 33.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.3.1.tar.gz (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.0/49.0 kB 33.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.3.0.tar.gz (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.0/49.0 kB 30.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.2.3.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 28.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.2.2.tar.gz (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 24.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.2.1.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.2.0.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.1.0.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.0.2.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.0.1.tar.gz (27 kB)
  Preparing metadata (setup.py) ... done
  Downloading distributed-1.0.0.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Collecting dask[array,diagnostics] (from quartical)
  Downloading dask-2023.4.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 93.7 MB/s eta 0:00:00
  Downloading dask-2023.3.2-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 86.4 MB/s eta 0:00:00
Collecting bokeh<3,>=2.4.2 (from dask[array,diagnostics]->quartical)
  Downloading bokeh-2.4.3-py3-none-any.whl (18.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 70.4 MB/s eta 0:00:00
Collecting typing-extensions>=3.10.0 (from bokeh<3,>=2.4.2->dask[array,diagnostics]->quartical)
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting dask[array,diagnostics] (from quartical)
  Downloading dask-2023.3.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 28.0 MB/s eta 0:00:00
  Downloading dask-2023.3.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 97.3 MB/s eta 0:00:00
  Downloading dask-2023.2.1-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 100.4 MB/s eta 0:00:00
  Downloading dask-2023.2.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 99.3 MB/s eta 0:00:00
  Downloading dask-2023.1.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 97.6 MB/s eta 0:00:00
  Using cached dask-2023.1.0-py3-none-any.whl (1.1 MB)
Collecting MarkupSafe>=2.0 (from jinja2>=2.10.3->dask[array,diagnostics]->quartical)
  Using cached MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting python-dateutil>=2.8.2 (from pandas>=1.3->xarray>=0.20.0->quartical)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas>=1.3->xarray>=0.20.0->quartical)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
````

**Comment by bennahugo** [comment]
Current numpy versions break, pinning to 1.21 fixes the below:
```
2023-05-03 21:05:19 | ERROR | goquartical:<module> | An error has been caught in function '<module>', process 'MainProcess' (175758), thread 'MainThread' (140247814154048):
Traceback (most recent call last):

> File "/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/bin/goquartical", line 8, in <module>
    sys.exit(execute())
    │   │    └ <function execute at 0x7f8ca5f6c550>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/lib/python3.8/site-packages/quartical/executor.py", line 29, in execute
    _execute(stack)
    │        └ <contextlib.ExitStack object at 0x7f8dfce2d190>
    └ <function _execute at 0x7f8ca5f6c5e0>
  File "/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/lib/python3.8/site-packages/quartical/executor.py", line 141, in _execute
    data_xds_list = finalise_flags(data_xds_list)
                    │              └ [<xarray.Dataset>
                    │                Dimensions:              (row: 9504, chan: 1024, dir: 1, corr: 4, uvw: 3,
                    │                                          ant: 32...
                    └ <function finalise_flags at 0x7f8cafb56820>
  File "/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/lib/python3.8/site-packages/quartical/flagging/flagging.py", line 40, in finalise_flags
    flag_col = flag_col.astype(np.bool)
               │        │      └ <module 'numpy' from '/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/lib/python3.8/site-packages/numpy/__init__....
               │        └ <function Array.astype at 0x7f8cb25ca160>
               └ dask.array<broadcast_to, shape=(9504, 1024, 4), dtype=int8, chunksize=(9504, 1024, 4), chunktype=numpy.ndarray>
  File "/home/bhugo/LunarPolarimetry/absleakage_study/venvquartical/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
                         │                └ 'bool'
                         └ {'object': "module 'numpy' has no attribute 'object'.\n`np.object` was a deprecated alias for the builtin `object`. To avoid ...

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by JSKenyon** [comment]
Thanks for the report! I was already sort of aware of this and it is partially fixed on the `v0.2.0-dev` branch. I am wary of pinning versions as the original source of all these problems is pinned versions in upstream packages. I am now simply relying on the upstream packages to install dependencies, rather than QC itself. This cuts down on the minutes of version checking. The more correct approach will be to move to something like poetry such that each release is associated with specific versions of dependencies.

**Comment by sjperkins** [comment]
Would making the dask-ms package version less restrictive be helpful?

**Comment by JSKenyon** [comment]
I am not sure - possibly. I actually need to sit down and check where the remaining conflicts come from. It may be that codex and dask-ms have different requirements, but don't quote me on that as I haven't checked.

**Comment by JSKenyon** [comment]
The source of the problem now stems from the fact that no upstream package installs `distributed`, but they do install `dask` with specific versioning requirements. This means that QC has to install `distributed` and the dependency resolver has to figure out which `distributed` works with the required `dask`. I am going to look at moving to poetry in an attempt to resolve this.

**Comment by JSKenyon** [comment]
This should be much less of an issue with the `v0.2.0` release due to upstream changes.
